image: robertcnelson/debian-bookworm-slim-riscv:latest

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - mirror/Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.6.1-20220906.tar.gz
    - deploy/*.tar.xz

build:
  tags:
    - docker-amd64
  stage: build
  script:
    - touch .gitlab-runner
    - ./01_git_sync.sh
    - ./02_build_opensbi.sh
    - ./03_build_uboot.sh
    - ./04_build_linux.sh
    - ./05_generate_boot.sh
    - ./06_generate_ubuntu_console_root.sh
    - xz -vT8 deploy/boot.ext4
    - xz -vT8 deploy/root.ext4
  artifacts:
    expire_in: 5 days
    name: "$CI_PROJECT_NAME-mainline-$CI_JOB_ID"
    paths:
      - "deploy/fastboot_emmc.sh"
      - "deploy/mac_fastboot_emmc.sh"
      - "deploy/u-boot-with-spl.bin"
      - "deploy/boot.ext4.xz"
      - "deploy/root.ext4.xz"

