image: robertcnelson/debian-bullseye-slim-riscv-debian:latest

before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan git.beagleboard.org >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

build:
  tags:
    - docker-amd64
  stage: build
  script:
    - touch .gitlab-runner
    - ./01_git_sync.sh
    - ./02_build_opensbi.sh
    - ./03_build_uboot.sh
    - ./04_build_linux.sh
    - ./05_generate_boot.sh
    - ./06_generate_ubuntu_xfce_root.sh
    - xz -vT8 deploy/boot.ext4
    - xz -vT8 deploy/root.ext4
  artifacts:
    expire_in: 5 days
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "deploy/fastboot_emmc.sh"
      - "deploy/u-boot-with-spl.bin"
      - "deploy/boot.ext4.xz"
      - "deploy/root.ext4.xz"

